[General]
__userfile__=true
desktop_show=false
theme=SprunglesQT

[desktopswitch]
alignment=Left
type=desktopswitch

[mainmenu]
alignment=Left
type=mainmenu

[taskbar]
alignment=Left
type=taskbar

[tray]
alignment=Right
type=tray

[worldclock]
alignment=Right
format=yyyy/MM/dd HH:mm
type=worldclock
tooltip_format=cccc yyyy/MM/dd
